<a href="https://colab.research.google.com/github/sumanu9400/Machine_learning/blob/main/Numpy%26Pandas__ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#machine learning numpy
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
b=np.array([[1,2,3,4],[1,2,3,4]])
b

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
b.ndim# dimensions

2

In [ ]:
a.ndim

1

In [ ]:
b.shape #(rows,col)

(2, 4)

In [ ]:
b.shape#(rows,col)

(5,)

In [ ]:
b.itemsize

8

In [ ]:
b.dtype

dtype('int64')

In [ ]:
b.itemsize

8

In [ ]:
b.nbytes


64

In [ ]:
c=np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]])
c

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
c[1,3]#(row,col)

4

In [ ]:
c[0,:]#total row

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
c[1,2]

3

In [ ]:
c[:,6]#specific total row

array([7, 7])

In [ ]:
d=np.array([[1,2,3,4,5],[1,2,3,4,6],[1,2,3,4,7]])
d

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 6],
       [1, 2, 3, 4, 7]])

In [ ]:
# prompt: d.ndim

d.ndim


2

In [ ]:
s=np.zeros([6,6])
s

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
d=np.full([2,3],99)
d

array([[99, 99, 99],
       [99, 99, 99]])

In [ ]:
e=np.random.rand(4,4)
e

array([[0.79288177, 0.74293399, 0.06263169, 0.05607755],
       [0.89625394, 0.47469352, 0.61788434, 0.25578996],
       [0.5520981 , 0.5101533 , 0.78617042, 0.29382889],
       [0.08784149, 0.52985241, 0.33009588, 0.65516917]])

In [ ]:
# prompt: c=identity(5)

import numpy as np

c = np.identity(5)
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
c=np.identity(6)
c

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
a=np.array([1,2,3,4,5])
b=a.copy()
b[0]=12
a


array([1, 2, 3, 4, 5])

In [ ]:
a=np.array([1,2,3,4,5])
b=a.copy()
b[0]=12
b


array([12,  2,  3,  4,  5])

In [ ]:
a+2


array([3, 4, 5, 6, 7])

In [ ]:
#pandas operations in machine learing

In [ ]:
import pandas as pd


In [ ]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

print("labels:",labels)
print("Mydata:",my_data)
print("Dictionary:",d)
print("Array:",arr)

labels: ['a', 'b', 'c']
Mydata: [10, 20, 30]
Dictionary: {'a': 10, 'b': 20, 'c': 30}
Array: [10 20 30]


In [ ]:
pd.Series(data=my_data)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(labels, my_data) # Correct

10    a
20    b
30    c
dtype: object

In [ ]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [ ]:
import numpy as np
numbers=[99,86,87,88,111,86,103,87,94,78,77,85,86]
x=np.mean(numbers)
print(x)


89.76923076923077


In [ ]:
import numpy as np
speed=[99,86,87,88,111,86,103,87,94,78,77,85,86]
x=np.median(speed)
print(x)


87.0


In [ ]:
from scify import stats
speed=[99,86,87,88,111,86,103,87,94,78,77,85,86]
x=stats.mode(speed)
print(x)